apiVersion: v1
kind: Service
metadata:
  name: starbucks-cashier-client-service 
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080 
  selector:
    name: starbucks-cashier-client